on:
  - pull_request
  - push

name: backwards compatibility

jobs:
  roave_bc_check:
    uses: roave/backward-compatibility-check-action@v2.4.0
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.2']
